// This file is generated by GoAdmin CLI adm.
package models

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "account" => http://localhost:9033/admin/info/account
// "business" => http://localhost:9033/admin/info/business
// "cluster" => http://localhost:9033/admin/info/cluster
//
// example end
var Generators = map[string]table.Generator{

	"account":  GetAccountTable,
	"business": GetBusinessTable,
	"cluster":  GetClusterTable,

	// generators end
}
